apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-app
  template:
    metadata:
      labels:
        app: aks-app
    spec:
      containers:
      - name: aks-app
        image: <ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>
        ports:
        - containerPort: 3000
        env:
        - name: ENABLE_CUSTOMER_B_FEATURE
          value: "false" # Default: feature off