name: Scale test

# on:
#   workflow_dispatch:

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prod
          
jobs:
  build:
    runs-on: arc-org-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_REGISTRY }}
        
  deploy-qa:
    runs-on: arc-org-runner-set
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'qa' && (startsWith(github.ref_name, 'rel/') || startsWith(github.ref_name, 'hotfix/'))
    environment: qa
    steps:
      - name: Get short commit ID
        id: get_commit
        run: |
          SHORT_COMMIT_ID=$(git rev-parse --short HEAD)
          echo "SHORT_COMMIT_ID=$SHORT_COMMIT_ID" >> $GITHUB_ENV
  # scale-test0:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     # - uses: actions/checkout@v3
  #     # - uses: actions/setup-python@v5 
  #     #   with:
  #     #     python-version: '3.13'
  #     - run: pip3 freeze
  #     - name: Run a one-line script
  #       run: echo scale test 0 finished!
  # scale-test1:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 1 finished!
  # scale-test2:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 2 finished!
  # scale-test3:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 3 finished!
  # scale-test4:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 4 finished!
