name: Scale test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-org-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      # - name: Login to Azure Container Registry
      #   run: az acr login --name ${{ secrets.ACR_REGISTRY }}

      - uses: azure/docker-login@v2
        with:
          login-server: "${{ secrets.ACR_REGISTRY }}.azurecr.io"
  # scale-test0:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     # - uses: actions/checkout@v3
  #     # - uses: actions/setup-python@v5 
  #     #   with:
  #     #     python-version: '3.13'
  #     - run: pip3 freeze
  #     - name: Run a one-line script
  #       run: echo scale test 0 finished!
  # scale-test1:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 1 finished!
  # scale-test2:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 2 finished!
  # scale-test3:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 3 finished!
  # scale-test4:
  #   runs-on: arc-org-runner-set
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: sudo apt update -y
  #     - name: Run a one-line script
  #       run: echo scale test 4 finished!
